# zh.begin
site_description: Documentation for Yueshu Graph Database
site_author: 悦数图数据库
site_name: 悦数图数据库手册 
site_url: https://docs.yueshu.com.cn/ 
docs_dir: docs-2.0-zh 
copyright: Copyright &copy; 2023 悦数图数据库 - 浙ICP备2020038915号
# zh.end

# en.begin
site_description: Documentation for NebulaGraph Database 
site_author: NebulaGraph
site_name: NebulaGraph Database Manual
site_url: https://ent-docs.nebula-graph.io/ 
docs_dir: docs-2.0-en
copyright: Copyright &copy; 2023 NebulaGraph - 浙ICP备20010487号
# en.end


# Configuration
theme:
  name: material
# zh.begin  
  custom_dir: docs-2.0-zh/overrides
# zh.end
# en.begin  
  custom_dir: docs-2.0-en/overrides
# en.end
  font:
    code: Source Code Pro
# zh.begin  
    text: Noto Sans Simplified Chinese
# zh.end 
# en.begin
    text: Noto Sans
# en.end 

# zh.begin
  logo: 'https://docs-cdn.nebula-graph.com.cn/figures/yueshu-ent-docs-2023-5-15.png'
  favicon: 'https://docs-cdn.nebula-graph.com.cn/figures/yueshu_favicon_230515.png'
# zh.end 
# en.begin  
  logo: 'https://docs-cdn.nebula-graph.com.cn/figures/vesoft-nebula-logo-white22-12-21.png'
  favicon: 'https://docs-cdn.nebula-graph.com.cn/figures/favicon.ico'
# en.end  
  # Change color in `stylesheets > extra.css`
  palette:
    - scheme: nebula
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.top
    - header.autohide
    - content.tabs.link
    - content.code.copy
# zh.begin    
  language: 'zh'
# zh.end  
# en.begin    
  language: 'en'
# en.end  

extra_css:
  - stylesheets/logo.css
  - stylesheets/note.css
  - stylesheets/extra.css
#  - css/version-select.css
  - stylesheets/pdf.css

# Extensions
markdown_extensions:
  - footnotes
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
#      toc_depth: 3
      permalink: true
      separator: "_"
  - mdx_truly_sane_lists
  - pymdownx.superfences
  - pymdownx.snippets:
# en.begin
      base_path: docs-2.0-en/reuse/
# en.end
# zh.begin
      base_path: docs-2.0-zh/reuse/
# zh.end
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  # collapse content
  - pymdownx.details

# Plugins
plugins:
  # 图片展示插件（https://github.com/blueswen/mkdocs-glightbox#usage）
  - glightbox:  
      zoomable: true
  - search # 企业版文档目前只能使用mkdocs material 原生搜索。algolia搜索暂不支持。      
  - macros:
# en.begin  
      include_dir: docs-2.0-en/reuse/
# en.end
# zh.begin  
      include_dir: docs-2.0-zh/reuse/
# zh.end        
  - git-revision-date-localized
# modify when release: 
#  - exclude:
# Exclude files with unix-style wildcards (globs)
#      glob:
# Exclude all files in a directory. The path starts with the directory name in docs-2.0, such as `20.appendix/*`.



  - with-pdf:
      cover_subtitle: v5.0.0      
      cover: true
      back_cover: true
      copyright: Copyright &copy; Yueshu Graph Technology -  All rights reserved.
# en.begin
      cover_logo: 'https://cloud-cdn.nebula-graph.com.cn/nebula-for-pdf.png'
      output_path: pdf/NebulaGraph_Enterprise.pdf
# en.end
# zh.begin
      cover_logo: 'https://docs-cdn.nebula-graph.com.cn/figures/yueshu_favicon_230515.png'
      output_path: pdf/yueshu-cn.pdf  
# zh.end

extra_javascript:
#  - js/version-select.js      
  - js/config.js
  - js/jquery.js
  - js/init.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # js about docs search logic
  - https://www-cdn.nebula-graph.com.cn/nebula-docs/nebula-docs.7e772ed81c779cacbefc.js

# modify when release: 
extra:
  version:
    provider: mike
  nebula:
    release: 3.6.0
    nightly: nightly
    master: master
    base20: 2.0
    base200: 2.0.0
    branch: release-3.6
    tag: v3.6.0
# zh.begin
    name: 悦数图数据库
# zh.end
# en.begin
    name: NebulaGraph
# en.end
  explorer:
    release: 3.6.0
    branch: release-3.6
    tag: v3.6.0
# zh.begin
    name: 悦数图探索
# zh.end
# en.begin
    name: NebulaGraph Explorer
# en.end
  exchange_ent:
    release: 3.6.0
    branch: release-3.6
    tag: v3.6.0
  exchange:
    release: 3.6.0
    branch: release-3.6
    tag: v3.6.0
  importer:
    release: 4.1.0
    branch: release-4.1
    tag: v4.1.0
  algorithm:
    release: 3.0.0
    branch: v3.0.0
    tag: v3.0.0
  plato:
    release: 3.6.0
    branch: release-3.6
    tag: v3.6.0
# zh.begin
    name: 悦数图计算
# zh.end
# en.begin
    name: NebulaGraph Analytics
# en.end
  sparkconnector:
    release: 3.6.0
    branch: release-3.6
    tag: v3.6.0
  flinkconnector:
    release: 3.5.0
    branch: release-3.5
    tag: v3.5.0
  dockercompose:
    release: 3.6.0
    branch: release-3.6
    tag: v3.6.0
  dashboard_ent:
    release: 3.5.0
    tag: v3.5.0
    branch: release-3.5
# zh.begin
    name: 悦数运维监控
# zh.end
# en.begin
    name: NebulaGraph Dashboard
# en.end
  console:
    release: 3.5.0
    branch: release-3.5
    tag: v3.5.0
  br_ent:
    release: 3.6.0
    tag: v3.6.0
    name: Backup&Restore
  agent:
    release: 3.6.1
    tag: v3.6.1
  cpp:
    release: 3.4.0
    branch: release-3.4
    tag: v3.4.0
  java:
    release: 3.6.1
    branch: release-3.6
    tag: v3.6.1
  python:
    release: 3.4.0
    branch: release-3.4
    tag: v3.4.0
  go:
    release: 3.6.1
    branch: release-3.6
    tag: v3.6.1
  bench:
    release: 1.2.0
    branch: release-1.2
    tag: v1.2.0
  operator:
    release: 1.7.2
    tag: v1.7.2
    branch: release-1.7
    upgrade_from: 3.5.0
    upgrade_to: 3.6.0
  exporter:
    release: 3.3.0
    branch: release-3.3
    tag: v3.3.0
  gateway:
    release: 3.4.0
    branch: release-3.4
    tag: v3.4.0
  bbox:
    release: 3.5.0
    branch: release-3.5
    tag: v3.5.0
# zh.begin
    name: 悦数黑匣子
# zh.end
# en.begin
    name: NebulaGraph BlackBox
# en.end
  cloud:
    azureRelease: 3.1.1 # Azure云兼容的最新内核版本
    aliyunRelease: 3.4.0 # 阿里云兼容的最新内核版本
    azureLatestRelease: 3.1.0 # 支持Azure云的最新文档版本
    aliyunLatestRelease: 3.4.0 # 支持阿里云的最新文档版本
    name: 悦数图数据库

# zh.begin
nav:
  - 产品介绍:
      - 什么是悦数图数据库: 

  - 快速开始:

  - GQL 指南:
      - GQL 概述:
        - section/index.md

      - 数据类型:
        - section/index.md
        - 对象类型:
          - 图类型:
          - 点类型:
          - 边类型:
          - 约束表类型:
        - 值类型:
          - 数值: 
          - 字符串:
          - 布尔值:
          - 时间:
          - 列表:
          - 路径:
          - 记录:    

      - 数据类型转换:
        - section/index.md
        - toBoolean:
        - toInteger:
        - toFloat:
        - toString:

      - 函数和表达式:
        - section/index.md
      
      - 数据定义（DDL）:
        - section/index.md
        - Schema:
        - Graph:
        - Graph type:

      - 数据修改 (DML):
        - section/index.md
        - Insert:
        - Set:
        - Remove:
        - Delete:
        - Match + DML

      - 数据查询（DQL）:
        - section/index.md
        - 查询语句:
        - 通用元素:
          - 子句: 
        - 谓词:  

      - 数据库管理:
        - section/index.md
        - 查询调优
        - SHOW 语句
        - KILL 语句

      - 索引:
        - section/index.md
        - 主键索引:
        - 普通索引:

      - 过程:

# nav.pdf.begin
  - PDF: ./pdf/yueshu-cn.pdf
# nav.pdf.end

# zh.end

# en.begin
nav:
  - GQL:
      - Overview:
        - gql-guide/overview/index.md
        - Keywords and identifiers: gql-guide/overview/keywords-identifiers.md
        - Example dataset: gql-guide/overview/example-dataset.md

      - Data types:
        - gql-guide/data-types/index.md
        - Object types:
          - Graph type: gql-guide/data-types/graph-type.md
          - Node type: gql-guide/data-types/node-type.md
          - Edge type: gql-guide/data-types/edge-type.md
          - Binding table type: gql-guide/data-types/binding-table-type.md
        - Value types:
          - Numeric type: gql-guide/data-types/numeric-type.md
          - Character string type: gql-guide/data-types/c-string-type.md
          - Boolean type: gql-guide/data-types/boolean-type.md
          - Temporal type: gql-guide/data-types/temporal-type.md
          - List type: gql-guide/data-types/list-type.md
          - Path type: gql-guide/data-types/path-type.md
          - Record type: gql-guide/data-types/record-type.md


      - Functions and expressions:
        - gql-guide/functions-and-expressions/index.md
        - Math functions: gql-guide/functions-and-expressions/math.md
        - String functions: gql-guide/functions-and-expressions/string.md
        - Date and time functions: gql-guide/functions-and-expressions/temporal.md
        - List functions: gql-guide/functions-and-expressions/list.md
        - Graph functions: gql-guide/functions-and-expressions/graph.md
      
      - Data defnition:
        - gql-guide/ddl/index.md
        - Graph:
          - CREATE GRAPH: gql-guide/ddl/graph/create.md
          - DROP GRAPH: gql-guide/ddl/graph/drop.md
        - Graph type:
          - CREATE GRAPH TYPE: gql-guide/ddl/graph-type/create.md
          - DROP GRAPH TYPE: gql-guide/ddl/graph-type/drop.md

      - Data manipulation:
        - gql-guide/dml/index.md

      - Data queries:
        - gql-guide/dql/index.md

      - Database administration:
        - gql-guide/data-admin/index.md
        - SHOW statements: gql-guide/data-admin/show.md
        - KILL statements: gql-guide/data-admin/kill.md

      - Indexes
        - gql-guide/indexes/index.md 



# nav.pdf.begin
  - PDF: ./pdf/NebulaGraph_Enterprise.pdf
# nav.pdf.end
# en.end
