name: deploy-all

on:
  push:
    paths-ignore:
      - 'docs-2.0-zh/**'
      - 'docs-2.0-en/**'
    branches:
    # Remember to add v before the following version number unless the version is master.
      - master

jobs:
  deploy-zh:
  # 这个master是什么含义？
    uses: ./.github/workflows/deploy-zh.yml@master

  deploy-en:
    uses: ./.github/workflows/deploy-en.yml@master
