name: Publish English docs via GitHub Pages
env:
  ACTIONTEST: 3.6.0
on:
  workflow_call:
    secrets:
      ENSITE_PASSWORD:
        required: true
  push:
    branches:
    # Remember to add v before the following version number unless the version is master.
      - v3.6.0
    paths:
      - 'docs-2.0-en/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all commits/branches for gitversion

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name : prepare
        run: sh ./prepare.sh

      - name: Git Config
        run: git config user.name ChrisChen2023 && git config user.email chris.chen@vesoft.com
          
      - name: Mike Deploy
        run: |
          python ./scripts/render_english_only.py
          git fetch origin gh-pages --depth=1 # fix mike's CI update
          mike list
          mike deploy ${{ env.ACTIONTEST }}  -p --rebase
      #   The set-default command is only applicable to the latest version and must be commented in older versions.
      #   mike set-default ${{ env.ACTIONTEST }} -p --rebase 

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.DEPLOY_TOKEN }}
      #     publish_dir: ./site

      - name: show English git branch
        run: |
          git branch
          git checkout .
          git checkout gh-pages
          
      - name: Compress
        run: |
          tar -vczf ent-docs.tar.gz ${{ env.ACTIONTEST }} versions.json *.html

      - name: Transfer
        uses: appleboy/scp-action@master
        with:
          host: 20.163.77.63
          username: azureuser
          password: ${{ secrets.ENSITE_PASSWORD }}
          port: 404
          source: ent-docs.tar.gz
          target: /var/www/

      - name: UnCompress
        uses: appleboy/ssh-action@master
        with:
          host: 20.163.77.63
          username: azureuser
          password: ${{ secrets.ENSITE_PASSWORD }}
          port: 404
          script: |
            mkdir -p /var/www/ent-docs/
            tar -xzf /var/www/ent-docs.tar.gz -C /var/www/ent-docs/
            mkdir -p /var/www/ent-docs/site/pdf/
            cp -f /var/www/ent-docs/${{ env.ACTIONTEST }}/pdf/NebulaGraph_Enterprise.pdf /var/www/ent-docs/site/pdf/NebulaGraph_Enterprise.pdf
      
