name: Publish Chinese docs via GitHub Pages and upload to server
env:
# Remember to add v before the following version number unless the version is master.
  ACTIONTEST: 3.6.0
on:
  workflow_call:
    secrets:
      ZHSITE_PASSWORD:
        required: true
      OSS_ID:
        required: true
      OSS_SECRET:
        required: true
      OSS_ENDPOINT:
        required: true
  push:
    branches:
      - v3.6.0
    paths:
      - 'docs-2.0-zh/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1 # fetch all commits/branches for gitversion

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name : prepare
        run: sh ./prepare.sh 

      - name: Git Config
        run: git config user.name ChrisChen2023 && git config user.email chris.chen@vesoft.com
 
          
      - name: Mike Deploy
        run: |
          python ./scripts/render_chinese_only.py
          git fetch origin gh-pages-zh --depth=1 # fix mike's CI update
          mike list
          mike deploy ${{ env.ACTIONTEST }} -b gh-pages-zh -p
      #   The set-default command is only applicable to the latest version and must be commented in older versions.  
      #  mike set-default ${{ env.ACTIONTEST }} -b gh-pages-zh -p
    
      - name: show Chinese git branches
        run: |
          git branch
          git checkout .
          git checkout gh-pages-zh
              

      - name: Compress
        run: |
          tar -vczf ent-docs.tar.gz ${{ env.ACTIONTEST }} versions.json *.html

      - name: Transfer
        uses: appleboy/scp-action@master
        with:
          host: 121.40.218.31
          username: root
          password: ${{ secrets.ZHSITE_PASSWORD }}
          port: 404
          source: ent-docs.tar.gz
          target: /var/www/

      - name: UnCompress
        uses: appleboy/ssh-action@master
        with:
          host: 121.40.218.31
          username: root
          password: ${{ secrets.ZHSITE_PASSWORD }}
          port: 404
          script: |
            mkdir -p /var/www/ent-docs/
            tar -xzf /var/www/ent-docs.tar.gz -C /var/www/ent-docs/
            mkdir -p /var/www/ent-docs/site/pdf/
            cp -f /var/www/ent-docs/${{ env.ACTIONTEST }}/pdf/yueshu-cn.pdf /var/www/ent-docs/site/pdf/yueshu-cn.pdf

      - name: Upload to OSS
        uses: vesoft-inc/upload-oss@master
        with:
          key-id: ${{ secrets.OSS_ID }}
          key-secret: ${{ secrets.OSS_SECRET }}
          endpoint: ${{ secrets.OSS_ENDPOINT }}
          bucket: yueshu-graph
          asset-path: ${{ env.ACTIONTEST }}/pdf/yueshu-cn.pdf
          target-path: general/yueshu-doc/${{ env.ACTIONTEST }}
